version: '3.8'

services:
  directus:
    container_name: directus
    image: directus/directus:latest
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - directus
    ports:
      - "8055:8055"
    volumes:
      - ./data/uploads:/directus/uploads
      - ./data/extensions:/directus/extensions
      - ./config.yaml:/directus/config.yaml
    environment:
      DB_CLIENT: pg
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directus

      CONFIG_PATH: '/directus/config.yaml'

  db:
    container_name: database
    image: postgis/postgis:14-master
    restart: unless-stopped
    networks:
      - directus
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - directus
    networks:
      - directus
    ports:
      - "80:80"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/conf.d/default.conf
      - /tmp/acme_challenge:/tmp/acme_challenge
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    profiles: [ "certbot" ]
    volumes:
      - /tmp/acme_challenge:/tmp/acme_challenge
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/tmp/acme_challenge --email grant@atriustech.com --agree-tos --no-eff-email --staging -d directus.autonomy.institute

  test:
    container_name: bitnami/git:latest
    image: certbot/certbot
    profiles: [ "test" ]
    command: renew --help

volumes:
  certbot-etc:
  certbot-var:

networks:
  directus:
