version: "3.8"

services:
  directus:
    environment:
      - PUBLIC_URL="https://directus.autonomy.institute/"

  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  certbot:
    command: certonly --webroot --webroot-path=/tmp/acme_challenge --email grant@atriustech.com --agree-tos --no-eff-email -d directus.autonomy.institute
